% rdf_plot.m
% Plot Radial Distribution function from LAMMPS output file
% Necessary inputs in setup section :)
% Favian Sun
% 9/13/2023
%% Setup
close all; clear variables;

fileName = "Logs/Z-density/Graphene/spc_atom_6x6.dens";
fileName2 = "Logs/Z-density/Graphene/C_atom_6x6.dens";

AIMD = "Logs/Z-density/Graphene/XDATCAR";

fspc = fopen(fileName);
fC = fopen(fileName2);
XDATCAR = fopen(AIMD);
%From cont.in
timestep = 0.5/1000;    %timestep in cont.in (ps)
numSteps = 500000;      %numSteps in cont.in
perStep = 10000;          %how many steps between each rdf print

numPrint = numSteps/perStep;

%Zbounds
zhi = 44;
zlo = 0;

scaling = zhi-zlo;

%x-y bounds
xlo = 0;
xhi = 14.75707;
ylo = 0;
yhi = 14.75707;    %MAG

area = (xhi-xlo)*(yhi-ylo);

%First 3 lines are autogenerated comments
fgetl(fspc);
fgetl(fspc);
fgetl(fspc);
fgetl(fC);
fgetl(fC);
fgetl(fC);
%Filter strength
mAvg_num = 10;

plotTime = 39;

%XDATCAR moving avg 
numStepXDAT = 2000;
%% Loop, Read, and Basic data analysis

time = NaN(numPrint ,1); %allocate some space based on how timesteps & steps per print
BinsSpc = cell(numPrint,4);
BinsC = cell(numPrint,4);
for i = 1:numPrint
    %nextLine = transpose(split(strtrim(fgetl(fid))));
    nextLine = cell2mat(textscan(fspc, '%f%f%f',1));
    time(i) = nextLine(1);
    numBinsSpc = nextLine(2);

    nextLine = cell2mat(textscan(fC, '%f%f%f',1));
    numBinsC = nextLine(2);

    BinsSpc(i,:) = textscan(fspc, '%f%f%f%f',numBinsSpc);
    BinsC(i,:) = textscan(fC, '%f%f%f%f',numBinsC);
end

firstStep = cell2mat(BinsSpc(1,:));

dz = (firstStep(2,2)-firstStep(1,2))*scaling;

%Moving Avg -- not necessary if avgs are taken within the LAMMPS simulation
BinsPrintSpc = cell2mat(BinsSpc(plotTime,:));
binsFinSpc = move_avg(BinsPrintSpc(:,4),ceil(numBinsSpc/1000)+1,true);

BinsPrintC = cell2mat(BinsC(plotTime,:));
binsFinC = move_avg(BinsPrintC(:,4),ceil(numBinsC/1000)+1,true);

center_CMD = sum(BinsPrintC(:,2).*BinsPrintC(:,3))./sum(BinsPrintC(:,3)).*scaling;

%% Read from XDATCAR

fgetl(XDATCAR); %Comment
fgetl(XDATCAR); %discard

x_vec = transpose(cell2mat(textscan(XDATCAR, '%f %f %f',1)));
y_vec = transpose(cell2mat(textscan(XDATCAR, '%f %f %f',1)));
z_vec = transpose(cell2mat(textscan(XDATCAR, '%f %f %f',1)));
lattice = [x_vec y_vec z_vec];
elem = textscan(XDATCAR, '%s %s %s %s %s',1);
elem_cnt = transpose(cell2mat(textscan(XDATCAR, '%f %f %f %f %f',1))); %hardset for 5 elements
atomCnt = sum(elem_cnt);
t_moveAvg = ones(atomCnt,3,numStepXDAT);
xyz = cell(4000,3);
xyz_avg = ones(atomCnt,4000);
idx = 1;
for j = 1:4000 %Hardset
    discard = textscan(XDATCAR, '%s %s %f',1);

    xyz(j,:) = textscan(XDATCAR, '%f%f%f',atomCnt);
    t_moveAvg(:,:,idx) = cell2mat(xyz(j,:));    
    xyz_avg(:,j) = sum(t_moveAvg(:,3,:),3)/numStepXDAT.*z_vec(3);
    idx = mod(idx,numStepXDAT)+1;
end
%Add up over time : 0
%z_avg_C = xyz_avg(140:end,4000);
%z_avg_O = xyz_avg(95:139,4000);
z_avg_C = reshape(t_moveAvg(140:end,3,:),[205-140+1,numStepXDAT]).*z_vec(3);
z_avg_O = reshape(t_moveAvg(95:139,3,:),[139-95+1,numStepXDAT]).*z_vec(3);

[countO,edgesO] = histcounts(z_avg_O,50);
[countC,edgesC] = histcounts(z_avg_C,6);

midO = ones(length(edgesO)-1,1);
midC = ones(length(edgesC)-1,1);
for i = 1:length(edgesO)-1
    midO(i) = (edgesO(i) + edgesO(i+1))/2;
end
for i = 1:length(edgesC)-1
    midC(i) = (edgesC(i) + edgesC(i+1))/2;
end
center_AIMD = sum(transpose(midC).*countC)/sum(countC);

dzO = edgesO(2)-edgesO(1);
dzC = edgesC(2)-edgesC(1);
area = 14.757*14.757; %6x6
densH2O = (countO./numStepXDAT)./(area.*dzO.*0.6022).*18.02;
densC = (countC./numStepXDAT)./(area.*dzC.*0.6022).*12.011;

%% Plot
figure(1);
hold on;
plot(BinsPrintSpc(:,2).*scaling-center_CMD,BinsPrintSpc(:,4),'r-');
plot(BinsPrintC(:,2).*scaling-center_CMD,BinsPrintC(:,4),'b');
plot(midO-center_AIMD,densH2O);
plot(midC-center_AIMD,densC);
xlabel("Z Distance (Angstrom)");
ylabel("Density (g/cm^3)");
title("Pyridinic Graphene");
legend(["Water - CMD" "C - CMD" "H2O - AIMD" "C - AIMD"]);
axis([-2 14 0 10]);
hold off;
figure(2);
hold on;
plot(BinsPrintSpc(:,2).*scaling-center_CMD,binsFinSpc,'r-');
plot(BinsPrintC(:,2).*scaling-center_CMD,binsFinC,'b');
plot(midO-center_AIMD,densH2O);
plot(midC-center_AIMD,densC);
xlabel("Z Distance (Angstrom)");
ylabel("Density (g/cm^3)");
legend(["Water - CMD" "C - CMD" "H2O - AIMD" "C - AIMD"]);
axis([-2 14 0 10]);
hold off;
fclose('all');