% rdf_plot.m
% Plot Radial Distribution function from LAMMPS output file
% Necessary inputs in setup section :)
% Favian Sun
% 9/13/2023
%% Setup
close all; clear variables;

fileName = "Logs/rdf/tip5p.rdf";
fid = fopen(fileName);

%From cont.in
timestep = 1/1000;    %timestep in cont.in (ps)
numSteps = 100000;      %numSteps in cont.in
perStep = 1000;          %how many steps between each rdf print

%First 3 lines are autogenerated comments
Comment1 = fgetl(fid);
Comment2 = fgetl(fid);
Comment3 = fgetl(fid);

%Filter strength
mAvg_num = 10;

%O-H cutoff to take out direct O-H bond ~1.2 Angstroms
cutOH = 120;

%% Loop, Read, and Basic data analysis

time = NaN(numSteps/perStep ,1); %allocate some space based on how timesteps & steps per print

rdf_ave_oo = NaN(numSteps/perStep ,1);
moving_ave_oo = NaN(numSteps/perStep ,1);

rdf_ave_hh = NaN(numSteps/perStep ,1);
moving_ave_hh = NaN(numSteps/perStep ,1);

rdf_ave_oh = NaN(numSteps/perStep ,1);
moving_ave_oh = NaN(numSteps/perStep ,1);

for i = 1:numSteps/perStep
    %nextLine = transpose(split(strtrim(fgetl(fid))));
    nextLine = cell2mat(textscan(fid, '%f%f',1));
    time(i) = nextLine(1);
    numBins = nextLine(2);
    %Bins = cell(numBins,4);
    % for j = 1:numBins
    %     Bins(j,:) = transpose(split(strtrim(fgetl(fid))));
    % end
    Bins = cell2mat(textscan(fid, '%f%f%f%f%f%f%f%f',numBins));

    BinsCutOH = Bins((Bins(:,4)) > 2,:);  %Cutoff set to when the coordination number increases above 2. 2 O-H per molec
    rdf_ave_oh(i) = sum((BinsCutOH(:,3)).*(BinsCutOH(:,2)))/sum((BinsCutOH(:,3)));
    BinsCutHH = Bins((Bins(:,6)) > 1.01,:);  %Cutoff set to when the coordination number increases above 1. 1 H/H interaction per molec
    rdf_ave_hh(i) = sum((BinsCutHH(:,5)).*(BinsCutHH(:,2)))/sum((BinsCutHH(:,5)));
    rdf_ave_oo(i) = sum((Bins(:,7)).*(Bins(:,2)))/sum((Bins(:,7)));

    %idxOHcut = find(diff(BinsTemp(:,4))==2,1);
    %Bins(idxOHcut+1,3,i) = 0;
    %idxHHcut = find(diff(BinsTemp(:,5))>=75,1);
    %Bins(idxHHcut+1,5,i) = 0;

end

time = time(~isnan(time),:)*timestep;
rdf_ave_oh = rdf_ave_oh(~isnan(rdf_ave_oh),:);

movingAvgList_oh = rdf_ave_oh(1).*ones(mAvg_num,1); %moving average of mAvg_num samples
movingAvgList_hh = rdf_ave_hh(1).*ones(mAvg_num,1); %moving average of mAvg_num samples
movingAvgList_oo = rdf_ave_oo(1).*ones(mAvg_num,1); %moving average of mAvg_num samples
idx = 2;
for i = 1:length(rdf_ave_oh)

    moving_ave_oh(i) = mean(movingAvgList_oh);
    movingAvgList_oh(idx) = rdf_ave_oh(i);

    moving_ave_hh(i) = mean(movingAvgList_hh);
    movingAvgList_hh(idx) = rdf_ave_hh(i);

    moving_ave_oo(i) = mean(movingAvgList_oo);
    movingAvgList_oo(idx) = rdf_ave_oo(i);

    idx = mod(idx,mAvg_num)+1;
end

movingAvgFinal_oh = BinsCut(1,3).*ones(numBins/50,1); %moving average of mAvg_num samples
movingAvgFinal_hh = Bins(1,5).*ones(numBins/50,1); %moving average of mAvg_num samples
movingAvgFinal_oo = Bins(1,7).*ones(numBins/50,1); %moving average of mAvg_num samples
finalRDF_oh = NaN(numBins-cutOH,1);
finalRDF_hh = NaN(numBins,1);
finalRDF_oo = NaN(numBins,1);
idx = 2;
for i = 1:numBins
    if i < (numBins - cutOH)
        finalRDF_oh(i) = mean(movingAvgFinal_oh);
        movingAvgFinal_oh(idx) = BinsCut(i,3);
    end

    finalRDF_hh(i) = mean(movingAvgFinal_hh);
    movingAvgFinal_hh(idx) = Bins(i,5);

    finalRDF_oo(i) = mean(movingAvgFinal_oo);
    movingAvgFinal_oo(idx) = Bins(i,7);

    idx = mod(idx,numBins/50)+1;
end


%% Plot
figure(1);
subplot(3,1,1);
plot(time,rdf_ave_oh); %Plot all time
title("O-H Average Radius Over Time");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)");
subplot(3,1,2);
plot(time,rdf_ave_hh); %Plot all time
title("H-H Average Radius Over Time");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)");
subplot(3,1,3);
plot(time,rdf_ave_oo); %Plot all time
title("O-O Average Radius Over Time");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)");

figure(2);
subplot(3,1,1);
plot(time(mAvg_num:end),moving_ave_oh(mAvg_num:end)); %Plot once moving avg has enough unique values
title("O-H Average Radius Over Time, filtered");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)");
subplot(3,1,2);
plot(time(mAvg_num:end),moving_ave_hh(mAvg_num:end)); %Plot once moving avg has enough unique values
title("H-H Average Radius Over Time, filtered");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)");
subplot(3,1,3);
plot(time(mAvg_num:end),moving_ave_oo(mAvg_num:end)); %Plot once moving avg has enough unique values
title("O-O Average Radius Over Time, filtered");
xlabel("Time (ps)");
ylabel("Average Radius (Angstrom)")

figure(3);
subplot(2,1,1);
plot(BinsCut(:,2),finalRDF_oh);
title("O,H Final Radial Distribution Function, filtered");
xlabel("Radius (angstrom)");
ylabel("g(r)");
subplot(2,1,2);
plot(BinsCut(:,2),BinsCut(:,3));
title("O,H Final Radial Distribution Function");
xlabel("Radius (angstrom)");
ylabel("g(r)");

figure(4);
subplot(2,1,1);
plot(Bins(:,2),finalRDF_hh);
title("H,H Final Radial Distribution Function, filtered");
xlabel("Radius (angstrom)");
ylabel("g(r)");
subplot(2,1,2);
plot(Bins(:,2),Bins(:,5));
title("H,H Final Radial Distribution Function");
xlabel("Radius (angstrom)");
ylabel("g(r)");

figure(5);
subplot(2,1,1);
plot(Bins(:,2),finalRDF_oo);
title("O,O Final Radial Distribution Function, filtered");
xlabel("Radius (angstrom)");
ylabel("g(r)");
subplot(2,1,2);
plot(Bins(:,2),Bins(:,7));
title("O,O Final Radial Distribution Function");
xlabel("Radius (angstrom)");
ylabel("g(r)");

fclose('all');